version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: peakefeeds_db
    restart: always
    environment:
      POSTGRES_USER: peakeuser
      POSTGRES_PASSWORD: peakepassword
      POSTGRES_DB: peakefeeds_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

volumes:
  postgres_data:

